services:
  - type: web
    name: food-explorer-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_new_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: food-explorer-db
          property: connectionString
    autoDeploy: true

databases:
  - name: food-explorer-db
    databaseName: foodexplorer
    user: foodexplorer_user

